baseURL = 'https://www.rosenboom.name/'
DefaultContentLanguage = 'en'
languageCode = 'en-us'
title = 'rosenboom.name'
timeZone = 'Europe/Berlin'
theme = 'beautifulhugo'
enableGitInfo = false

[params]
  selfHosted = true
  logo = 'images/great_wave_off_kanagawa_100x100.webp'
  since = 2009
  mainSections = ['']
  rss = false
  comments = false
  readingTime = false
  wordCount = false
  useHLJS = false
  socialShare = false
  hideAuthor = true
  [params.author]
    name = 'Manfred Rosenboom'
    website = 'https://mastodon.social/@maroph'

#  [[menus.main]]
#    name = 'About'
#    pageRef = 'pages/about'
#    weight = 2
#  [[menus.main]]
#    parent = 'About'
#    name = 'Manfred'
#    url = 'pages/about/manfred'
#    weight = 3

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
    respectDoNotTrack = true
  [privacy.instagram]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.x]
    disable = true
  [privacy.youTube]
    disable = true

[taxonomies]
  tag = ''
  category = ''

